language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: zqTTsdAWi8xEvj/sr+WejahftQvpQrwxKT/v1xSmnii+XOA4c8ZR66OXX1SnzHGaakdbZpmxNd2GrNxVh7BBWlAaxLfApZpNoGLrJVwlP225j6xQ2xK69CArYx8QjNRU7GCuJFwpjR3I57LFBktHKrTAc/l1NFilSIVh5YKajtAgsmhL6ko9+ib0OV56EhtmWQo2mJaF8M42s311y/uW7S01nrtXFMDDrpiXF/eDCyE5vm+2fSl+ARcboA2J9SDIODJ3YIAfWzywYuI9mf/wafMD0gr6aYAJFxlxBqBb8fOuZu70JcKArhibKI/Y8fvhSxhSrx9d1q+03heQEFK96Yv9To8KnWz38bu8DUTGZ+fOblyK3zHgLuwQsdmyrZqP13VVt/KH2yYXaYAewrs3NdpSJClxSkagHe2xGkQxKoz6qQTw/nPaT/W4sgcCjzzT1qwNVLCBgChVnPTJvo6Rirf9TyP0OKEaM2n4rUvV+3OjNbH7Dma2VELp/YPCQwGHG0yUZwQ1u/S7xHOgBNV456WvOXv+fo6IDU5E8AnxSMj/+fLySUjO52v8tO602cRgdOJGDwM2Dr/gO8PcEEy+qS8D3xQSX3m+OYWW4/824H20VuagrrVQuJeDNObW6U8byKOuHlvkUCcuMBZmBMnhfNoyWcxyU7zD6Tn2L8d8GVY=
